# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f9e6ff14edab6502ce771e95ff663edc7be21329227f63e411a974c85adcb5117f81511bb431e75173eb3536ee3e8debf1a881c0ef30ba4741a7a6aec7dbc77

test:
  secret_key_base: 1da732fafc3383ce2e5d2bccc00be903f877201b1af1728b78b3cb475b7e65862fa64a1795836abadf4f443a40cdc6875e1766bed35a703bd4b67696c85cc4be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
